### ISSUE TITLE
Blank line after %% @private

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_format#164] opened 2020-09-25 00:33 UTC
I usually write my `edoc` related "tag" like so
```erlang
-spec resolve(Module :: module(), Host :: dispatcher:host()) ->
                 {ok, [inet:ip_address()]}.
%% @private
resolve(Module, Host) ->
    Module:resolve(Host).
```
This is getting formatted to
```erlang
-spec resolve(Module :: module(), Host :: dispatcher:host()) ->
                 {ok, [inet:ip_address()]}.
%% @private

resolve(Module, Host) ->
    Module:resolve(Host).
```

Is seems like a bug, but I'm not sure.

**Comment by elbrujohalcon** [comment] 2020-09-25 06:51
Duplicate of #165

**Closed by elbrujohalcon** 2020-09-25 06:51 UTC
Labels: duplicate

**Comment by paulo-ferraz-oliveira** [comment] 2020-09-25 09:45
> Duplicate of #165

This was surely GitHub acting up. I didn't drink last night.
