### ISSUE TITLE
Incorrect format when macro is used while building a binary

### ISSUE THREAD

**Issue by tgrk** [AdRoll/rebar3_format#81] opened 2020-02-25 21:59 UTC
I was able to successfully reformat quite a big codebase and have to say only one thing - What a great job!

The only issue that I found is that I had multiple syntax issues with this pattern:
```erlang
<<?i2b(IntegerValue)/binary, " foobar">>
```
instead of correct one:
```erlang
<<(?i2b(IntegerValue))/binary, " foobar">>
```
`?i2b/1` macro is just a conversion from integer to binary using BIF function without any wrapper. 

Thank you again for a great tool! :pray:

**Comment by elbrujohalcon** [comment] 2020-02-26 07:00
Probably a duplicate of #74 . @tgrk please confirm.

**Comment by hommeabeil** [comment] 2020-03-09 15:40
I can confirm there is an error in the binary, consider those lines,

```erlang
-define(CHUNK_SIZE, 65535 - 1).

chunkify(<<Binary:(?CHUNK_SIZE)/binary, Rest/binary>>) ->
    some code ...
```
Its get reformat as, which is invalide:
```erlang
chunkify(<<Binary:?CHUNK_SIZE/binary, Rest/binary>>) ->
```

**Comment by elbrujohalcon** [comment] 2020-03-10 08:31
Right, so… when fixing #74, we'll probably fix this one, too.

**Comment by hommeabeil** [comment] 2020-03-13 09:44
For my case it is.

**Comment by elbrujohalcon** [comment] 2020-04-28 11:00
This is not the same issue as #74, which deals with removing parentheses from _within_ macro definitions.
This one deals with removing parentheses when macros are treated as variables in expressions. This one will be really hard to solve.

**Closed** 2021-05-10 05:59 UTC
Labels: bug
