### ISSUE TITLE
Error in parsing `*.xrl`

### ISSUE THREAD

**Issue by vkatsuba** [AdRoll/rebar3_format#289] opened 2021-11-21 11:13 UTC
**Describe the bug**
Currently formatter works not good with `*.xrl` files and provide crash.

**To Reproduce**
* Create `*.xrl`:
```erlang

%%====================================================================
%% Definitions
%%====================================================================
Definitions.

String = '([^']*?)'

%%====================================================================
%% Rules
%%====================================================================
Rules.

%% =============================================================================
%% Erlang Code
%% =============================================================================
Erlang code.

strip_value(Value) ->
    io:format("~p", [Value]).
```
* Run `rebar3_format`:
```sh
$ rebar3 format
===> Error parsing files: {modified_ast,"src/some.xrl",
                                     "src/some.xrl"}
Stack: [{rebar3_ast_formatter,format,3,
                              [{file,"/some/_build/default/plugins/rebar3_format/src/rebar3_ast_formatter.erl"},
                               {line,40}]},
        {rebar3_format_prv,'-format_files/2-fun-0-',2,
                           [{file,"/some/_build/default/plugins/rebar3_format/src/rebar3_format_prv.erl"},
                            {line,125}]},
        {lists,'-filter/2-lc$^0/1-0-',2,[{file,"lists.erl"},{line,1290}]},
        {rebar3_format_prv,format_files,2,
                           [{file,"/some/_build/default/plugins/rebar3_format/src/rebar3_format_prv.erl"},
                            {line,123}]},
        {rebar3_format_prv,do,1,
                           [{file,"/some/_build/default/plugins/rebar3_format/src/rebar3_format_prv.erl"},
                            {line,43}]},
        {rebar_core,do,2,
                    [{file,"/home/runner/work/rebar3/rebar3/src/rebar_core.erl"},
                     {line,155}]},
        {rebar3,run_aux,2,
                [{file,"/home/runner/work/rebar3/rebar3/src/rebar3.erl"},
                 {line,182}]},
        {rebar3,main,1,
                [{file,"/home/runner/work/rebar3/rebar3/src/rebar3.erl"},
                 {line,66}]}]
=ERROR REPORT==== 21-Nov-2021::13:08:17.860648 ===
    modified_ast: src/mql_scanner.xrl
    removed: [{error,no}]
    added: [{tree,no,
                  {attr,no,[],none},
                  "* * 6 : unterminated atom starting with '\\n\\n%%============' * *"}]
===> Unknown Formatting Error: {modified_ast,"src/some.xrl",
                              "src/some.xrl"}
```
* Output of file:
```erlang
%%====================================================================
%% Definitions
%%====================================================================
Definitions.

** 6: unterminated atom starting with '\n\n%%============' **
```
**Expected behavior**
The `rebar3_format` do parse `*.xrl` files as well.

**Comment by vkatsuba** [comment] 2021-11-21 11:14
Hm.. looks like this is not implemented. https://github.com/AdRoll/rebar3_format/issues/246.

**Comment by elbrujohalcon** [comment] 2021-11-22 06:37
Exactly. I'll close this as a duplicate of #246.

**Closed by elbrujohalcon** 2021-11-22 06:37 UTC
Labels: bug
