### ISSUE TITLE
Strange indentation of andalso guards

### ISSUE THREAD

**Issue by facundoolano** [AdRoll/rebar3_format#209] opened 2020-11-13 15:04 UTC
**Describe the bug**
I got the following diff when running the 0.7.0 version of the formatter:

<img width="888" alt="Screen Shot 2020-11-13 at 11 59 30 AM" src="https://user-images.githubusercontent.com/1040941/99086147-e06df200-25a7-11eb-8e8c-8b36e9c6f86a.png">

**To Reproduce**
Try to format a function with multiline guards using `andalso`:

```erlang
range({A, B, C, D} = IP, Mask) when A >= 0 andalso A =< 255 andalso
                                    B >= 0 andalso B =< 255 andalso
                                    C >= 0 andalso C =< 255 andalso
                                    D >= 0 andalso D =< 255 ->
  ok.
```

**Expected behavior**
I would expect the output format to use the same indentation for all the guard lines.

**Comment by paulo-ferraz-oliveira** [comment] 2020-11-14 10:59
Might it be related to https://github.com/AdRoll/rebar3_format/issues/185?

**Comment by elbrujohalcon** [comment] 2020-11-14 12:47
Yeah. It's actually a duplicate of that one. Good catch, @paulo-ferraz-oliveira !

**Closed by elbrujohalcon** 2020-11-14 12:47 UTC
Labels: bug
