### ISSUE TITLE
Formatter remove single quotes from macros containing dashes

### ISSUE THREAD

**Issue by carlosedp** [AdRoll/rebar3_format#310] opened 2022-06-13 13:31 UTC
**Describe the bug**

Formatter remove single quotes from macros containing dashes.

**To Reproduce**

The code below:

```erlang
-define(CCR_INITIAL, ?'CC-REQUEST-TYPE_INITIAL_REQUEST').
-define(CCR_UPDATE, ?'CC-REQUEST-TYPE_UPDATE_REQUEST').
-define(CCR_TERMINATE, ?'CC-REQUEST-TYPE_TERMINATION_REQUEST').
-define(MSISDN, ?'SUBSCRIPTION-ID-TYPE_END_USER_E164').
-define(IMSI, ?'SUBSCRIPTION-ID-TYPE_END_USER_IMSI').
```

becomes:

```erlang
-define(DCCA_APPLICATION_ID, 4).
-define(CCR_INITIAL, ?CC-REQUEST-TYPE_INITIAL_REQUEST).
-define(CCR_UPDATE, ?CC-REQUEST-TYPE_UPDATE_REQUEST).
-define(CCR_TERMINATE, ?CC-REQUEST-TYPE_TERMINATION_REQUEST).
-define(MSISDN, ?SUBSCRIPTION-ID-TYPE_END_USER_E164).
-define(IMSI, ?SUBSCRIPTION-ID-TYPE_END_USER_IMSI).
```

Without the single quotes, making the code unable to compile.

**Expected behavior**

Do not remove quotes from macros that have dashes. This doesn't happen when using erlfmt external formatter.

**Rebar3 Log**
Run rebar3 with `DEBUG=1` and paste its output here.

**Additional context**

Below the format config in my rebar.config:

```erl
{format, [
    {files, ["apps/*/{src,include,test}/*.{erl,hrl,app.src}", "**/{rebar,sys}.config"]},
    % {formatter, erlfmt_formatter},
    {options, #{
        paper => 100,
        print_width => 100,
        ignore_pragma => true
    }}
]}.
```

**Comment by elbrujohalcon** [comment] 2022-06-13 13:41
Duplicate of #311

**Closed by elbrujohalcon** 2022-06-13 13:41 UTC
Labels: bug
